version: '3'

networks:
  dev:

services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./
    ports:
      - '${FRONTEND_PORT_LOCAL}:${VITE_PORT}'
    networks:
      - dev
    command: npm start
