version: '3'

networks:
  dev:

services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./
    ports:
      - 5173:5173
    networks:
      - dev
    command: npm start
